server:
  port: 10000

spring:
  application:
    name: gateway
  cloud:
    discovery:
      enabled: true

eureka:
  client:
    healthcheck:
      enabled: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://localhost:8761}/eureka/

zuul:
  ignored-services: "*"
  prefix: /api
  routes:
    service-api:
      path: /service/**
      stripPrefix: true
    legacy-api:
      path: /legacy/**
      stripPrefix: true
  ribbonIsolationStrategy: THREAD
  threadPool:
    useSeparateThreadPools: true

filters:
  auth-filter:
    enabled: true

#service-api:
#  ribbon:
#    eureka:
#      enabled: true
#    NIWSServerListClassName: com.netflix.niws.loadbalancer.DiscoveryEnabledNIWSServerList
#    ConnectTimeout: 5000
#    ReadTimeout: 5000
#    MaxTotalHttpConnections: 500
#    MaxConnectionsPerHost: 100

#zuul:
#  routes:
#    service-1:
#      path: /service-1/**
#      url: http://localhost:10001
#    service-2:
#      path: /service-2/**
#      url: http://localhost:10002

#logging:
#  level:
#    root: debug
